// Tabelas de domínio do PNCP (códigos e nomes usados nas consultas).
// Servidas localmente pela ferramenta pncp_tabelas_dominio, sem chamada de rede.
export const DOMAIN_TABLES = {
  instrumento_convocatorio: [
    { codigo: 1, nome: "Edital", descricao: "Diálogo competitivo, concurso, concorrência, pregão, manifestação de interesse, pré-qualificação e credenciamento" },
    { codigo: 2, nome: "Aviso de Contratação Direta", descricao: "Dispensa com Disputa" },
    { codigo: 3, nome: "Ato que autoriza a Contratação Direta", descricao: "Dispensa sem Disputa ou Inexigibilidade" },
  ],

  modalidade_contratacao: [
    { codigo: 1, nome: "Leilão - Eletrônico" },
    { codigo: 2, nome: "Diálogo Competitivo" },
    { codigo: 3, nome: "Concurso" },
    { codigo: 4, nome: "Concorrência - Eletrônica" },
    { codigo: 5, nome: "Concorrência - Presencial" },
    { codigo: 6, nome: "Pregão - Eletrônico" },
    { codigo: 7, nome: "Pregão - Presencial" },
    { codigo: 8, nome: "Dispensa de Licitação" },
    { codigo: 9, nome: "Inexigibilidade" },
    { codigo: 10, nome: "Manifestação de Interesse" },
    { codigo: 11, nome: "Pré-qualificação" },
    { codigo: 12, nome: "Credenciamento" },
    { codigo: 13, nome: "Leilão - Presencial" },
  ],

  modo_disputa: [
    { codigo: 1, nome: "Aberto" },
    { codigo: 2, nome: "Fechado" },
    { codigo: 3, nome: "Aberto-Fechado" },
    { codigo: 4, nome: "Dispensa Com Disputa" },
    { codigo: 5, nome: "Não se aplica" },
    { codigo: 6, nome: "Fechado-Aberto" },
  ],

  criterio_julgamento: [
    { codigo: 1, nome: "Menor preço" },
    { codigo: 2, nome: "Maior desconto" },
    { codigo: 4, nome: "Técnica e preço" },
    { codigo: 5, nome: "Maior lance" },
    { codigo: 6, nome: "Maior retorno econômico" },
    { codigo: 7, nome: "Não se aplica" },
    { codigo: 8, nome: "Melhor técnica" },
    { codigo: 9, nome: "Conteúdo artístico" },
  ],

  situacao_contratacao: [
    { codigo: 1, nome: "Divulgada no PNCP", descricao: "Situação atribuída na inclusão da contratação" },
    { codigo: 2, nome: "Revogada" },
    { codigo: 3, nome: "Anulada" },
    { codigo: 4, nome: "Suspensa" },
  ],

  situacao_item_contratacao: [
    { codigo: 1, nome: "Em Andamento", descricao: "Disputa/seleção do fornecedor não finalizada" },
    { codigo: 2, nome: "Homologado", descricao: "Com resultado (fornecedor informado)" },
    { codigo: 3, nome: "Anulado/Revogado/Cancelado" },
    { codigo: 4, nome: "Deserto", descricao: "Sem fornecedores interessados" },
    { codigo: 5, nome: "Fracassado", descricao: "Fornecedores desclassificados ou inabilitados" },
  ],

  tipo_beneficio: [
    { codigo: 1, nome: "Participação exclusiva para ME/EPP" },
    { codigo: 2, nome: "Subcontratação para ME/EPP" },
    { codigo: 3, nome: "Cota reservada para ME/EPP" },
    { codigo: 4, nome: "Sem benefício" },
    { codigo: 5, nome: "Não se aplica" },
  ],

  situacao_resultado_item_contratacao: [
    { codigo: 1, nome: "Informado", descricao: "Possui valor, fornecedor e marca oriundo do resultado" },
    { codigo: 2, nome: "Cancelado" },
  ],

  tipo_contrato: [
    { codigo: 1, nome: "Contrato (termo inicial)", descricao: "Acordo formal recíproco entre as partes" },
    { codigo: 2, nome: "Comodato", descricao: "Concessão de uso gratuito de bem móvel ou imóvel" },
    { codigo: 3, nome: "Arrendamento", descricao: "Cessão de bem por período mediante pagamento" },
    { codigo: 4, nome: "Concessão", descricao: "Serviço público com remuneração por tarifa" },
    { codigo: 5, nome: "Termo de Adesão", descricao: "Cláusulas não negociáveis" },
    { codigo: 6, nome: "Convênio", descricao: "Objetivo em comum entre as partes" },
    { codigo: 7, nome: "Empenho", descricao: "Promessa de pagamento pelo Estado" },
    { codigo: 8, nome: "Outros" },
    { codigo: 9, nome: "Termo de Execução Descentralizada (TED)", descricao: "Descentralização de crédito entre órgãos" },
    { codigo: 10, nome: "Acordo de Cooperação Técnica (ACT)", descricao: "Execução de programas de trabalho" },
    { codigo: 11, nome: "Termo de Compromisso" },
    { codigo: 12, nome: "Carta Contrato", descricao: "Formaliza acordo em hipóteses que a lei dispensa contrato" },
  ],

  tipo_termo_contrato: [
    { codigo: 1, nome: "Termo de Rescisão", descricao: "Encerramento antes da data final" },
    { codigo: 2, nome: "Termo Aditivo", descricao: "Atualiza o contrato (prorrogação, reajuste, acréscimo, supressão)" },
    { codigo: 3, nome: "Termo de Apostilamento", descricao: "Atualiza o valor do contrato" },
  ],

  categoria_processo: [
    { codigo: 1, nome: "Cessão" },
    { codigo: 2, nome: "Compras" },
    { codigo: 3, nome: "Informática (TIC)" },
    { codigo: 4, nome: "Internacional" },
    { codigo: 5, nome: "Locação Imóveis" },
    { codigo: 6, nome: "Mão de Obra" },
    { codigo: 7, nome: "Obras" },
    { codigo: 8, nome: "Serviços" },
    { codigo: 9, nome: "Serviços de Engenharia" },
    { codigo: 10, nome: "Serviços de Saúde" },
    { codigo: 11, nome: "Alienação de bens móveis/imóveis" },
  ],

  tipo_documento: [
    { codigo: 1, nome: "Aviso de Contratação Direta", categoria: "contratacao" },
    { codigo: 2, nome: "Edital", categoria: "contratacao" },
    { codigo: 3, nome: "Minuta do Contrato", categoria: "contratacao_anexo" },
    { codigo: 4, nome: "Termo de Referência", categoria: "contratacao_anexo" },
    { codigo: 5, nome: "Anteprojeto", categoria: "contratacao_anexo" },
    { codigo: 6, nome: "Projeto Básico", categoria: "contratacao_anexo" },
    { codigo: 7, nome: "Estudo Técnico Preliminar", categoria: "contratacao_anexo" },
    { codigo: 8, nome: "Projeto Executivo", categoria: "contratacao_anexo" },
    { codigo: 9, nome: "Mapa de Riscos", categoria: "contratacao_anexo" },
    { codigo: 10, nome: "DFD", categoria: "contratacao_anexo" },
    { codigo: 11, nome: "Ata de Registro de Preço", categoria: "ata" },
    { codigo: 12, nome: "Contrato", categoria: "contrato" },
    { codigo: 13, nome: "Termo de Rescisão", categoria: "contrato" },
    { codigo: 14, nome: "Termo Aditivo", categoria: "contrato" },
    { codigo: 15, nome: "Termo de Apostilamento", categoria: "contrato" },
    { codigo: 16, nome: "Outros documentos do processo", categoria: "geral" },
    { codigo: 17, nome: "Nota de Empenho", categoria: "contrato" },
    { codigo: 18, nome: "Relatório Final de Contrato", categoria: "contrato" },
  ],

  porte_empresa: [
    { codigo: 1, nome: "ME", descricao: "Microempresa" },
    { codigo: 2, nome: "EPP", descricao: "Empresa de Pequeno Porte" },
    { codigo: 3, nome: "Demais", descricao: "Demais empresas" },
    { codigo: 4, nome: "Não se aplica", descricao: "Fornecedor pessoa física" },
    { codigo: 5, nome: "Não informado" },
  ],

  categoria_item_pca: [
    { codigo: 1, nome: "Material" },
    { codigo: 2, nome: "Serviço" },
    { codigo: 3, nome: "Obras" },
    { codigo: 4, nome: "Serviços de Engenharia" },
    { codigo: 5, nome: "Soluções de TIC" },
    { codigo: 6, nome: "Locação de Imóveis" },
    { codigo: 7, nome: "Alienação/Concessão/Permissão" },
    { codigo: 8, nome: "Obras e Serviços de Engenharia" },
  ],

  amparo_legal: [
    { codigo: 1, nome: "Lei 14.133/2021, Art. 28, I" },
    { codigo: 2, nome: "Lei 14.133/2021, Art. 28, II" },
    { codigo: 3, nome: "Lei 14.133/2021, Art. 28, III" },
    { codigo: 4, nome: "Lei 14.133/2021, Art. 28, IV" },
    { codigo: 5, nome: "Lei 14.133/2021, Art. 28, V" },
    { codigo: 6, nome: "Lei 14.133/2021, Art. 74, I" },
    { codigo: 7, nome: "Lei 14.133/2021, Art. 74, II" },
    { codigo: 8, nome: "Lei 14.133/2021, Art. 74, III, a" },
    { codigo: 9, nome: "Lei 14.133/2021, Art. 74, III, b" },
    { codigo: 10, nome: "Lei 14.133/2021, Art. 74, III, c" },
    { codigo: 11, nome: "Lei 14.133/2021, Art. 74, III, d" },
    { codigo: 12, nome: "Lei 14.133/2021, Art. 74, III, e" },
    { codigo: 13, nome: "Lei 14.133/2021, Art. 74, III, f" },
    { codigo: 14, nome: "Lei 14.133/2021, Art. 74, III, g" },
    { codigo: 15, nome: "Lei 14.133/2021, Art. 74, III, h" },
    { codigo: 16, nome: "Lei 14.133/2021, Art. 74, IV" },
    { codigo: 17, nome: "Lei 14.133/2021, Art. 74, V" },
    { codigo: 18, nome: "Lei 14.133/2021, Art. 75, I" },
    { codigo: 19, nome: "Lei 14.133/2021, Art. 75, II" },
    { codigo: 20, nome: "Lei 14.133/2021, Art. 75, III, a" },
    { codigo: 21, nome: "Lei 14.133/2021, Art. 75, III, b" },
    { codigo: 22, nome: "Lei 14.133/2021, Art. 75, IV, a" },
    { codigo: 23, nome: "Lei 14.133/2021, Art. 75, IV, b" },
    { codigo: 24, nome: "Lei 14.133/2021, Art. 75, IV, c" },
    { codigo: 25, nome: "Lei 14.133/2021, Art. 75, IV, d" },
    { codigo: 26, nome: "Lei 14.133/2021, Art. 75, IV, e" },
    { codigo: 27, nome: "Lei 14.133/2021, Art. 75, IV, f" },
    { codigo: 28, nome: "Lei 14.133/2021, Art. 75, IV, g" },
    { codigo: 29, nome: "Lei 14.133/2021, Art. 75, IV, h" },
    { codigo: 30, nome: "Lei 14.133/2021, Art. 75, IV, i" },
    { codigo: 31, nome: "Lei 14.133/2021, Art. 75, IV, j" },
    { codigo: 32, nome: "Lei 14.133/2021, Art. 75, IV, k" },
    { codigo: 33, nome: "Lei 14.133/2021, Art. 75, IV, l" },
    { codigo: 34, nome: "Lei 14.133/2021, Art. 75, IV, m" },
    { codigo: 35, nome: "Lei 14.133/2021, Art. 75, V" },
    { codigo: 36, nome: "Lei 14.133/2021, Art. 75, VI" },
    { codigo: 37, nome: "Lei 14.133/2021, Art. 75, VII" },
    { codigo: 38, nome: "Lei 14.133/2021, Art. 75, VIII" },
    { codigo: 39, nome: "Lei 14.133/2021, Art. 75, IX" },
    { codigo: 40, nome: "Lei 14.133/2021, Art. 75, X" },
    { codigo: 41, nome: "Lei 14.133/2021, Art. 75, XI" },
    { codigo: 42, nome: "Lei 14.133/2021, Art. 75, XII" },
    { codigo: 43, nome: "Lei 14.133/2021, Art. 75, XIII" },
    { codigo: 44, nome: "Lei 14.133/2021, Art. 75, XIV" },
    { codigo: 45, nome: "Lei 14.133/2021, Art. 75, XV" },
    { codigo: 46, nome: "Lei 14.133/2021, Art. 75, XVI" },
    { codigo: 47, nome: "Lei 14.133/2021, Art. 78, I" },
    { codigo: 48, nome: "Lei 14.133/2021, Art. 78, II" },
    { codigo: 49, nome: "Lei 14.133/2021, Art. 78, III" },
    { codigo: 50, nome: "Lei 14.133/2021, Art. 74, caput" },
    { codigo: 51, nome: "Lei 14.284/2021, Art. 29, caput" },
    { codigo: 52, nome: "Lei 14.284/2021, Art. 24 § 1º" },
    { codigo: 53, nome: "Lei 14.284/2021, Art. 25 § 1º" },
    { codigo: 54, nome: "Lei 14.284/2021, Art. 34" },
    { codigo: 55, nome: "Lei 9.636/1998, Art. 11-C, I" },
    { codigo: 56, nome: "Lei 9.636/1998, Art. 11-C, II" },
    { codigo: 57, nome: "Lei 9.636/1998, Art. 24-C, I" },
    { codigo: 58, nome: "Lei 9.636/1998, Art. 24-C, II" },
    { codigo: 59, nome: "Lei 9.636/1998, Art. 24-C, III" },
    { codigo: 60, nome: "Lei 14.133/2021, Art. 75, XVII" },
    { codigo: 61, nome: "Lei 14.133/2021, Art. 76, I, a" },
    { codigo: 62, nome: "Lei 14.133/2021, Art. 76, I, b" },
    { codigo: 63, nome: "Lei 14.133/2021, Art. 76, I, c" },
    { codigo: 64, nome: "Lei 14.133/2021, Art. 76, I, d" },
    { codigo: 65, nome: "Lei 14.133/2021, Art. 76, I, e" },
    { codigo: 66, nome: "Lei 14.133/2021, Art. 76, I, f" },
    { codigo: 67, nome: "Lei 14.133/2021, Art. 76, I, g" },
    { codigo: 68, nome: "Lei 14.133/2021, Art. 76, I, h" },
    { codigo: 69, nome: "Lei 14.133/2021, Art. 76, I, i" },
    { codigo: 70, nome: "Lei 14.133/2021, Art. 76, I, j" },
    { codigo: 71, nome: "Lei 14.133/2021, Art. 76, II, a" },
    { codigo: 72, nome: "Lei 14.133/2021, Art. 76, II, b" },
    { codigo: 73, nome: "Lei 14.133/2021, Art. 76, II, c" },
    { codigo: 74, nome: "Lei 14.133/2021, Art. 76, II, d" },
    { codigo: 75, nome: "Lei 14.133/2021, Art. 76, II, e" },
    { codigo: 76, nome: "Lei 14.133/2021, Art. 76, II, f" },
    { codigo: 77, nome: "Lei 14.133/2021, Art. 75, XVIII" },
    { codigo: 78, nome: "Lei 14.628/2023, Art. 4º" },
    { codigo: 79, nome: "Lei 14.628/2023, Art. 12" },
    { codigo: 80, nome: "Lei 14.133/2021, Art. 1º, § 2º" },
  ],
} as const;

export type DomainTableKey = keyof typeof DOMAIN_TABLES;

export function getDomainTable(tabela: string): unknown {
  if (tabela in DOMAIN_TABLES) {
    return DOMAIN_TABLES[tabela as DomainTableKey];
  }
  return {
    erro: `Tabela '${tabela}' não encontrada.`,
    tabelas_disponiveis: Object.keys(DOMAIN_TABLES),
  };
}

export const TABELAS_DISPONIVEIS = Object.keys(DOMAIN_TABLES);
